name: hz_camera
description: hz camera Flutter plugin.
version: 0.0.1
homepage: https://github.com/wa143825/hz_camera

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.plugin.hz_camera
        pluginClass: HzCameraPlugin
      ios:
        pluginClass: HzCameraPlugin
